[project]
name = "experiment-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "experimaestro>=1.7.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
